using Medallion.Threading.Tests.Data;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Medallion.Threading.Tests.Data
{
    public class SqlReaderWriter_AlternateClientConnectionTest : SqlDistributedReaderWriterLockTestCases<AlternateClientConnectionProvider> { }
    public class SqlReaderWriter_AlternateClientTransactionTest : SqlDistributedReaderWriterLockTestCases<AlternateClientTransactionProvider> { }
    public class SqlReaderWriter_AzureConnectionStringTest : SqlDistributedReaderWriterLockTestCases<AzureConnectionStringProvider> { }
    public class SqlReaderWriter_ConnectionBasedConnectionStringTest : SqlDistributedReaderWriterLockTestCases<ConnectionBasedConnectionStringProvider> { }
    public class SqlReaderWriter_DefaultClientConnectionTest : SqlDistributedReaderWriterLockTestCases<DefaultClientConnectionProvider> { }
    public class SqlReaderWriter_DefaultClientTransactionTest : SqlDistributedReaderWriterLockTestCases<DefaultClientTransactionProvider> { }
    public class SqlReaderWriter_DefaultConnectionStringTest : SqlDistributedReaderWriterLockTestCases<DefaultConnectionStringProvider> { }
    public class SqlReaderWriter_MultiplexedConnectionStringTest : SqlDistributedReaderWriterLockTestCases<MultiplexedConnectionStringProvider> { }
    public class SqlReaderWriter_NoStrategyConnectionStringTest : SqlDistributedReaderWriterLockTestCases<NoStrategyConnectionStringProvider> { }
    public class SqlReaderWriter_TransactionBasedConnectionStringTest : SqlDistributedReaderWriterLockTestCases<TransactionBasedConnectionStringProvider> { }
    public class SqlSemaphore_AlternateClientConnectionTest : SqlDistributedSemaphoreTestCases<AlternateClientConnectionProvider> { }
    public class SqlSemaphore_AlternateClientTransactionTest : SqlDistributedSemaphoreTestCases<AlternateClientTransactionProvider> { }
    public class SqlSemaphore_AzureConnectionStringTest : SqlDistributedSemaphoreTestCases<AzureConnectionStringProvider> { }
    public class SqlSemaphore_ConnectionBasedConnectionStringTest : SqlDistributedSemaphoreTestCases<ConnectionBasedConnectionStringProvider> { }
    public class SqlSemaphore_DefaultClientConnectionTest : SqlDistributedSemaphoreTestCases<DefaultClientConnectionProvider> { }
    public class SqlSemaphore_DefaultClientTransactionTest : SqlDistributedSemaphoreTestCases<DefaultClientTransactionProvider> { }
    public class SqlSemaphore_DefaultConnectionStringTest : SqlDistributedSemaphoreTestCases<DefaultConnectionStringProvider> { }
    public class SqlSemaphore_MultiplexedConnectionStringTest : SqlDistributedSemaphoreTestCases<MultiplexedConnectionStringProvider> { }
    public class SqlSemaphore_NoStrategyConnectionStringTest : SqlDistributedSemaphoreTestCases<NoStrategyConnectionStringProvider> { }
    public class SqlSemaphore_TransactionBasedConnectionStringTest : SqlDistributedSemaphoreTestCases<TransactionBasedConnectionStringProvider> { }
    public class SqlSemaphoreSelfDeadlock_AlternateClientConnectionTest : SqlDistributedSemaphoreSelfDeadlockTestCases<AlternateClientConnectionProvider> { }
    public class SqlSemaphoreSelfDeadlock_AlternateClientTransactionTest : SqlDistributedSemaphoreSelfDeadlockTestCases<AlternateClientTransactionProvider> { }
    public class SqlSemaphoreSelfDeadlock_DefaultClientConnectionTest : SqlDistributedSemaphoreSelfDeadlockTestCases<DefaultClientConnectionProvider> { }
    public class SqlSemaphoreSelfDeadlock_DefaultClientTransactionTest : SqlDistributedSemaphoreSelfDeadlockTestCases<DefaultClientTransactionProvider> { }
}

namespace Medallion.Threading.Tests.Postgres
{
    public class Core_Db_Postgres_ExternalDbConnectionStrategy_Postgres_Postgres_PostgresTest : DistributedLockCoreTestCases<TestingDbLockProvider<PostgresProvider, TestingExternalDbConnectionStrategyProvider<PostgresProvider, PostgresProvider>, PostgresProvider>> { }
    public class Core_Db_Postgres_ExternalDbTransactionStrategy_Postgres_Postgres_PostgresTest : DistributedLockCoreTestCases<TestingDbLockProvider<PostgresProvider, TestingExternalDbTransactionStrategyProvider<PostgresProvider, PostgresProvider>, PostgresProvider>> { }
    public class Core_Db_Postgres_OwnConnectionStrategy_Postgres_PostgresTest : DistributedLockCoreTestCases<TestingDbLockProvider<PostgresProvider, TestingOwnConnectionStrategyProvider<PostgresProvider>, PostgresProvider>> { }
    public class Core_Db_Postgres_OwnTransactionConnectionStrategy_Postgres_PostgresTest : DistributedLockCoreTestCases<TestingDbLockProvider<PostgresProvider, TestingOwnTransactionConnectionStrategyProvider<PostgresProvider>, PostgresProvider>> { }
}

namespace Medallion.Threading.Tests.SqlServer
{
    public class AzureConnectionStrategy_SqlEngineFactoryTest : AzureConnectionStrategyTestCases<TestingSqlDistributedLockEngineFactory> { }
    public class AzureConnectionStrategy_SqlReaderWriterEngineFactoryTest : AzureConnectionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory> { }
    public class AzureConnectionStrategy_SqlSemaphoreEngineFactoryTest : AzureConnectionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory> { }
    public class ConnectionStringStrategy_SqlEngineFactory_AzureConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, AzureConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlEngineFactory_ConnectionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, ConnectionBasedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlEngineFactory_DefaultConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, DefaultConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlEngineFactory_MultiplexedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, MultiplexedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlEngineFactory_NoStrategyConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, NoStrategyConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlEngineFactory_TransactionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedLockEngineFactory, TransactionBasedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_AzureConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, AzureConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_ConnectionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, ConnectionBasedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_DefaultConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, DefaultConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_MultiplexedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, MultiplexedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_NoStrategyConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, NoStrategyConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlReaderWriterEngineFactory_TransactionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, TransactionBasedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_AzureConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, AzureConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_ConnectionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, ConnectionBasedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_DefaultConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, DefaultConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_MultiplexedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, MultiplexedConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_NoStrategyConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, NoStrategyConnectionStringProvider> { }
    public class ConnectionStringStrategy_SqlSemaphoreEngineFactory_TransactionBasedConnectionStringTest : ConnectionStringStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, TransactionBasedConnectionStringProvider> { }
    public class Core_Db_SqlServer_ExternalDbConnectionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>> { }
    public class Core_Db_SqlServer_ExternalDbConnectionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>> { }
    public class Core_Db_SqlServer_ExternalDbTransactionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>> { }
    public class Core_Db_SqlServer_ExternalDbTransactionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>> { }
    public class Core_Db_SqlServer_OwnConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingOwnConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>> { }
    public class Core_Db_SqlServer_OwnTransactionConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingDbLockProvider<SqlServerProvider, TestingOwnTransactionConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_ExternalDbConnectionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_ExternalDbConnectionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_ExternalDbTransactionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_ExternalDbTransactionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_OwnConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingOwnConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_ReaderWriterAsMutex_DbReaderWriter_SqlServer_OwnTransactionConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingReaderWriterLockAsMutexProvider<TestingDbReaderWriterLockProvider<SqlServerProvider, TestingOwnTransactionConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_ExternalDbConnectionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_ExternalDbConnectionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_ExternalDbTransactionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_ExternalDbTransactionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_OwnConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingOwnConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore1AsMutex_DbSemaphore_SqlServer_OwnTransactionConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore1AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingOwnTransactionConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_ExternalDbConnectionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_ExternalDbConnectionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbConnectionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_ExternalDbTransactionStrategy_SqlServer_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_ExternalDbTransactionStrategy_SqlServer_SystemDataSqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingExternalDbTransactionStrategyProvider<SqlServerProvider, SystemDataSqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_OwnConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingOwnConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class Core_Semaphore5AsMutex_DbSemaphore_SqlServer_OwnTransactionConnectionStrategy_SqlServer_SqlServerTest : DistributedLockCoreTestCases<TestingSemaphore5AsMutexProvider<TestingDbSemaphoreProvider<SqlServerProvider, TestingOwnTransactionConnectionStrategyProvider<SqlServerProvider>, SqlServerProvider>>> { }
    public class ExternalConnectionOrTransactionStrategy_SqlEngineFactory_AlternateClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlEngineFactory_AlternateClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlEngineFactory_DefaultClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlEngineFactory_DefaultClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, DefaultClientTransactionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlReaderWriterEngineFactory_AlternateClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlReaderWriterEngineFactory_AlternateClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlReaderWriterEngineFactory_DefaultClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlReaderWriterEngineFactory_DefaultClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, DefaultClientTransactionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlSemaphoreEngineFactory_AlternateClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlSemaphoreEngineFactory_AlternateClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlSemaphoreEngineFactory_DefaultClientConnectionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalConnectionOrTransactionStrategy_SqlSemaphoreEngineFactory_DefaultClientTransactionTest : ExternalConnectionOrTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, DefaultClientTransactionProvider> { }
    public class ExternalConnectionStrategy_SqlEngineFactory_AlternateClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedLockEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionStrategy_SqlEngineFactory_DefaultClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedLockEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalConnectionStrategy_SqlReaderWriterEngineFactory_AlternateClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionStrategy_SqlReaderWriterEngineFactory_DefaultClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalConnectionStrategy_SqlSemaphoreEngineFactory_AlternateClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, AlternateClientConnectionProvider> { }
    public class ExternalConnectionStrategy_SqlSemaphoreEngineFactory_DefaultClientConnectionTest : ExternalConnectionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, DefaultClientConnectionProvider> { }
    public class ExternalTransactionStrategy_SqlEngineFactory_AlternateClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalTransactionStrategy_SqlEngineFactory_DefaultClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory, DefaultClientTransactionProvider> { }
    public class ExternalTransactionStrategy_SqlReaderWriterEngineFactory_AlternateClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalTransactionStrategy_SqlReaderWriterEngineFactory_DefaultClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory, DefaultClientTransactionProvider> { }
    public class ExternalTransactionStrategy_SqlSemaphoreEngineFactory_AlternateClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, AlternateClientTransactionProvider> { }
    public class ExternalTransactionStrategy_SqlSemaphoreEngineFactory_DefaultClientTransactionTest : ExternalTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory, DefaultClientTransactionProvider> { }
    public class MultiplexingConnectionStrategy_SqlEngineFactoryTest : MultiplexingConnectionStrategyTestCases<TestingSqlDistributedLockEngineFactory> { }
    public class MultiplexingConnectionStrategy_SqlReaderWriterEngineFactoryTest : MultiplexingConnectionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory> { }
    public class MultiplexingConnectionStrategy_SqlSemaphoreEngineFactoryTest : MultiplexingConnectionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory> { }
    public class OwnedTransactionStrategy_SqlEngineFactoryTest : OwnedTransactionStrategyTestCases<TestingSqlDistributedLockEngineFactory> { }
    public class OwnedTransactionStrategy_SqlReaderWriterEngineFactoryTest : OwnedTransactionStrategyTestCases<TestingSqlDistributedReaderWriterLockEngineFactory> { }
    public class OwnedTransactionStrategy_SqlSemaphoreEngineFactoryTest : OwnedTransactionStrategyTestCases<TestingSqlDistributedSemaphoreEngineFactory> { }
}

namespace Medallion.Threading.Tests.WaitHandles
{
    public class Core_EventWaitHandleTest : DistributedLockCoreTestCases<TestingEventWaitHandleLockProvider> { }
}